# Generated by Django 4.1.7 on 2023-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='viki_link',
            field=models.TextField(default=''),
        ),
    ]
