# Generated by Django 4.1.7 on 2023-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_rename_viki_link_animal_wiki_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='wiki_link',
            field=models.TextField(),
        ),
    ]
