# Generated by Django 4.1.7 on 2023-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_category_animal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'Зверь', 'verbose_name_plural': 'Звери'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='URL'),
        ),
    ]
