# Generated by Django 4.1.7 on 2023-04-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_animal_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='wiki_link',
            field=models.TextField(verbose_name='Ссылка на википедию'),
        ),
    ]
